### ISSUE TITLE
GitHub login not working

### ISSUE THREAD

**Issue by dnkennedy** [OpenNeuroLab/brainspell-neo#66]
I was trying out the new BrainSpell neo app from: https://brainspell.herokuapp.com/ (looks nice, by the way...)

When selecting the 'Login with GitHub' link I get an error:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/app/.heroku/python/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/app/.heroku/python/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/app/.heroku/python/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/app/brainspell/github_collections.py", line 89, in get
    client_id=settings[settings_key_id],
NameError: name 'settings_key_id' is not defined

Curious what I'm doing wrong...

**Comment by neelsomani** [comment]
Hi @dnkennedy, sorry about this - I pushed a change that should fix the issue.
